version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  postgis:
    image: mapcentia/postgis
    volumes:
      - postgis_var_lib_postgresql:/var/lib/postgresql
    networks:
      - internal
      - web
#    ports:
#      - "5432:5432"
    environment:
      - GC2_USER=gc2
      - GC2_PASSWORD=1234

volumes:
  postgis_var_lib_postgresql:




